logging:
  level:
    root: info

springdoc:
  swagger-ui:
    operations-sorter: method

spring:
  config:
    import: optional:file:.env[.properties]
  elasticsearch:
    uris: http://elasticsearch-node-1:9200,http://elasticsearch-node-2:9200,http://elasticsearch-node-3:9200
  data:
    mongodb:
      uri: mongodb://mongodb-node-1,mongodb-node-2,mongodb-node-3/traintickets
    redis:
      cluster:
        nodes: redis-node-1:6379,redis-node-2:6379,redis-node-3:6379